#! /bin/sh

$HOME/.config/bspwm/autostart.sh

# monitors
bspc monitor eDP-1 -d I II III IV V VI VII


# configs
bspc config border_width         0
bspc config window_gap           12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 40


# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on


# remap keys
setxkbmap -option ctrl:swapcaps
setxkbmap -option ctrl:nocaps
