#! /bin/sh

$HOME/.config/bspwm/autostart.sh

# monitors
bspc monitor eDP-1 -d I II III IV V VI VII
bspc monitor HDMI-1 -d VIII IX


# configs
bspc config border_width            1
bspc config focused_border_color    "#FF8C00" #darkorange
bspc config window_gap              12
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config pointer_motion_interval 40


# rules
bspc rule -a TelegramDesktop desktop='^4' follow=on


# remap keys
setxkbmap -option ctrl:swapcaps
setxkbmap -option ctrl:nocaps

# java app configs
wmname LG3D
